### ISSUE TITLE
MVPリリースのレビュー依頼

### ISSUE THREAD

**Issue by matsudaron** [matsudaron/Finding_art#30]
## 各種情報
FINDING_Art
https://finding-art.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
＜MVPまでに完成させたい機能＞
- [x] ・アカウント作成機能
- [x] ・ログイン機能
- [x] ・投稿機能
- [ ] ・リアクション機能
- [x] ・マイリスト追加（お気に入り）機能

## READMEレビュー時から変更した機能
・リアクション機能は未実装（よく考えたらお気に入り機能との差別化ができなかった）
・投稿記事の検索機能を追加
※Googleマップは実装してみましたが、まだエラーが出ている&MVPリリース時点では実装を考えていなかったためこのままリリースいたします

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/513026ffc121582a9c0ea52c0587b607.jpg)](https://gyazo.com/513026ffc121582a9c0ea52c0587b607)
管理者画面はありません。

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
投稿に関して行ってみたところ、「住所は不正な値です」と出続けています。こちらはどんな入力値が想定されていますか？

<img width="1254" alt="スクリーンショット 2024-06-29 18 06 05" src="https://github.com/matsudaron/Finding_art/assets/108249057/01654b23-bd80-4a24-bd3f-031b632329d4">

（タイトル等は、画像に合わせたものになっております。アートがなく配慮できず申し訳ございません）

**Comment by matsudaron** [comment]
@kashiwagi-rena 
ご指摘ありがとうございます。
こちらの原因ですが、どうやら中途半端に実装していたGoogleマップが原因のようでした。
開発環境では上手く機能していたマップが、デプロイ環境だとfor development purposes onlyと表示されてしまい上手く動かなかったことも起因していると考えています。
あれこれ試してみて、やはり機能改善が見込めなかったため一旦Googleマップ機能を削除して再度提出をいたしました。
よろしくお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
